# Site settings
title: "Retina Mac Apps"
description: "Load up your new Retina Mac with these awesome apps"
baseurl: ""
url: "https://retinamacapps.com"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE', '.ruby-version']

# Build settings
markdown: kramdown